ACE_LICENSE=L-RJGW-BUAA2R
ACE_NAMESPACE=cp4i-ace
INTEGRATION_RUNTIME=flight-landing-simulator-cflt
KAFKA_SCRAM_USER=kafka-admin
KAFKA_SCRAM_PASSWORD=FVVOYHlgDGE3V0QNUPaoX317
BOOTSTRAP_URL=163.66.92.248:9094,163.66.92.248:9095,163.66.92.248:9096
